.PHONY: payloads

CC ?= clang

payloads:
	@xxd -iC Pongo.bin > Pongo.h
	@xxd -iC shellcode.bin > shellcode.h
	@xxd -iC yolo_s8000.bin > yolo_s8000.h
	@xxd -iC yolo_s8001.bin > yolo_s8001.h
	@xxd -iC yolo_s8003.bin > yolo_s8003.h
	@xxd -iC yolo_t7000.bin > yolo_t7000.h
	@xxd -iC yolo_t7001.bin > yolo_t7001.h
	@xxd -iC yolo_t8010.bin > yolo_t8010.h
	@xxd -iC yolo_t8011.bin > yolo_t8011.h
	@xxd -iC yolo_t8015.bin > yolo_t8015.h
